### ISSUE TITLE
Top of iOS app shows antoher color

### ISSUE THREAD

**Issue by Nicxe** [arsaboo/oxford_blue_theme#1]
The top of the iOS app shows another color than the menu. I have set the theme in a automation when HASS starts up using `frontend.set_theme`, that usually dose the trick, but not whit this theme. Is there anything in the team that controls this?

![06D25DBF-DD98-45B3-B8BE-8D3BB0B3F0CB_1_201_a](https://user-images.githubusercontent.com/27124316/71740950-dba3c200-2e5d-11ea-9e05-fbaf1a1b927b.jpeg)

**Comment by arsaboo** [comment]
I am not sure what is causing this. I will dig deeper to find out. Thanks for highlighting the issue.

**Comment by robbiet480** [comment]
iOS app only supports the following value types:

```
“abc”
“abc7”
”#abc7”
“00FFFF”
”#00FFFF”
“00FFFF77”
“Orange”, “Azure”, “Tomato” Modern browsers support 140 color names (http://www.w3schools.com/cssref/css_colornames.asp)
“Clear” [UIColor clearColor]
“Transparent” [UIColor clearColor]
nil [UIColor clearColor]
empty string [UIColor clearColor]
```

@arsaboo is fixing this now.

**Comment by arsaboo** [comment]
Done....thanks @robbiet480

**Comment by Nicxe** [comment]
Thanks 🙏
